Handle the upgrade from ulogd to ulogd2 in jessie and later.
Use augeas to handle modifying the existing ulogd2 logrotate config.

Remove instead of purge ulogd because it deletes log files on purge.

Remove the puppet installed logrotate config for ulogd.

Eliminates mails like these:

/etc/cron.daily/logrotate:
error: ulogd2:1 duplicate log entry for /var/log/ulog/syslogemu.log